[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read-write", path = "./out" },
    { access = "read", path = "./templates" }
]

[fmt]
line_length = 120
multiline_func_header = 'all'